### ISSUE TITLE
Expand the task overview page

### ISSUE THREAD

**Issue by arneboockmeyer** [openHPI/codeocean#11]
Some information would also be useful:
- Nr. of tests
- Sum of points

**Comment by hklement** [comment]
Do you mean the exercise instructions for learners or the back-end view for instructors?

**Comment by arneboockmeyer** [comment]
The back end ;)

**Comment by hklement** [comment]
Implemented in commit 2f69e2f3103d8a2d70ec883eda0aefde63bca47b.
