### ISSUE TITLE
Vagrant script fails after new postgresql version 14 became available

### ISSUE THREAD

**Issue by KlausGPaul** [openHPI/codeocean#1101]
## Problem

When running the `vagrant up` script as suggested in the documentation, the build failed with an error message
```
default: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
```

The resulting VM did not function.

## Expected behaviour

Build results in a working VM.

## Steps to reproduce

Will happen for new vagrant runs ever since postgres 14 was released and became available

## Root Cause

This is due to line 30 of `provision.vagrant.sh` is configured to set up passwordless logins for localhost in a folder `/etc/postgresql/$postgres_version/main/pg_hba.conf` with `$postgres_version` being set to 13.

## Possible fix outline

There is two ways to fix it, either set the version to 14 in line 6, or call for an explicit version ` install -y postgresql-client-$postgres_version postgresql-$postgres_version` in line 27, or (better) a combination of both.

**Comment by MrSerth** [comment]
Many thanks for your detailed bug report and the proposed solution. I followed your suggestion and created a new PR with the changes. As I am currently not running a Vagrant setup, would you be kind enough to provide some feedback on my changes in #1102? Thank you
