### ISSUE TITLE
[Security] Workflow ci.yml is using vulnerable action paambaati/codeclimate-action

### ISSUE THREAD

**Issue by fockboi-lgtm** [openHPI/codeocean#1114]
The workflow ci.yml is referencing action paambaati/codeclimate-action using references v2.7.4. However this reference is missing the commit [62e5eab9c1f8c952f64862c152e205c9c835b755](https://github.com/paambaati/codeclimate-action/commits/62e5eab9c1f8c952f64862c152e205c9c835b755) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by MrSerth** [comment]
Thanks for notifying! I updated the action `paambaati/codeclimate-action` to the newest version available (`v3.0.0`) with commits 78ffb1be and 0f92e862.
