### ISSUE TITLE
Localize feedback message

### ISSUE THREAD

**Issue by arneboockmeyer** [openHPI/codeocean#13]
If a test has no errors, the following messages comes: Well done. All tests have been passed.
Please translate this to german for the java course.

**Comment by tstaubitz** [comment]
Just checked. The correct translations are all there in the locales.
I also can't find something wrong in the code where they are used.
Still, you're right. The sentence is not translated.

**Comment by hklement** [comment]
There seems to be an issue with concurrent processing. The feedback message is sometimes localized when the correct locale is not set yet. Commit b8284a7a2624600c743ff682ecc15f3b9625a57a should fix this.

**Comment by tstaubitz** [comment]
fixed
