### ISSUE TITLE
Do not use Xikolo APIv1 for authentication

### ISSUE THREAD

**Issue by franzliedke** [openHPI/codeocean#137]
Please avoid talking to the obsolete APIv1, for authenticating (see [this line](https://github.com/openHPI/codeocean/blob/b384dffe3467d1ea5890af457f0571efbe091510/lib/xikolo/client.rb#L57)).

Our app developers can tell you how to authenticate against the new API.

Can you do it within the next four weeks? I'd like to move towards shutting off the old API in December (and I'm gone for almost all of ~December~November).

**Comment by rteusner** [comment]
So I should talk with Tobi oder Max?

**Comment by tstaubitz** [comment]
I guess you can talk to either of them.

**Comment by franzliedke** [comment]
Yes, either of them. Any status update here? :innocent:

**Comment by rteusner** [comment]
As far as I know, we do not use the API at all right now. We switched to LTI in order to transfer user data to CodeOcean and then just use local data.
