### ISSUE TITLE
All exercises accessible by URL manipulation

### ISSUE THREAD

**Issue by flokX** [openHPI/codeocean#140]
If you are signed in in the CodeOcean, you can switch between all excercises by changing the URL.

Ways to reproduce the bug:
1. Sign in to the CodeOcean by doing an exercise in openHPI
2. Now you can simply switch between different excercises by changing the excercise number: `https://codeocean.openhpi.de/exercises/[try random numbers]/implement`

**Comment by tstaubitz** [comment]
Why do you consider this to be a bug? As far as we are concerned, it is ok to work on as many exercises as you want. You probably will run into a problem, however, if you try to submit the results of an exercises that you accessed by tampering with the URL to the LMS from which you started the initial exercise, if you're not using the platform standalone.

**Comment by flokX** [comment]
In my opinion it's never good to get access to areas you don't need, but if it's a conscious decision I am going to close this PR.

**Comment by franzliedke** [comment]
@tstaubitz This would actually help a lot to prevent some of the problems CodeOcean has had in regards to returning the right result for the wrong exercise.

Authentication via LTI should only ever give you access to exactly one exercise (i.e. the one identified by the provided token). If others weren't accessible, results could not be submitted incorrectly.

**Comment by MrSerth** [comment]
I might have a look at this issue when checking the integration of multiple exercises on a worksheet but won't promise anything.
