### ISSUE TITLE
Prevent Score  Button Spamming

### ISSUE THREAD

**Issue by mpass99** [openHPI/codeocean#1733]
In the recent [POSEIDON-G](https://codeocean.sentry.io/issues/2817059136) events it seems like CodeOcean requested a file system update for the same runner 19 times in parallel. All the requests fail in the same second as the runner is stopped.

Significant about the case `29-57f217dc-0ad2-11ee-a4f7-fa163e079f19` is also how it was possible that CodeOcean could start 11 executions in 3 second that all run into the timeout of 30 seconds.

<hr>

It seems like we are observing a user-triggered behavior in this case. For example, view [this transaction](https://codeocean.sentry.io/performance/codeocean-frontend:3d1970baf4274e69a7bde325ca021916/?project=4505177156354048&transaction=assess) that clearly shows the many `assess` runs triggered by the JavaScript frontend.

<hr>

We decided to implement a quick fix in the CodeOcean frontend by removing the event listener from the button until a score run completed.

**Comment by MrSerth** [comment]
We are tackling this issue as part of #1648, and have it implemented already in #1698.

**Comment by MrSerth** [comment]
Since we are now blocking runners with openHPI/codeocean#1982, this issue should be resolved, too.
