### ISSUE TITLE
Update proforma gem to v0.9

### ISSUE THREAD

**Issue by MrSerth** [openHPI/codeocean#1812]
@kkoehn: Would you mind taking a look at the dependency update for CodeOcean as well, please? 

I don't know whether there is much to check here -- potentially, we don't need any code adjustments since just the test configuration was added (which we ignore in CodeOcean), but I haven't verified that.

**Comment by MrSerth** [comment]
Unfortunately, it seems like we should do the upgrade in CodeOcean rather quickly. As of now, Dependabot is no longer able to generate automatic pull requests and I would hope that the issue resolved once proforma is updated.

**Comment by kkoehn** [comment]
Sorry for the delay
I agree there shouldn't be any changes necessary for CO

**Comment by MrSerth** [comment]
Don't worry, all good. Happy to have the upgrade now.
