### ISSUE TITLE
WebSocket connection closed without (our custom) closing frame in case of a timeout

### ISSUE THREAD

**Issue by mpass99** [openHPI/codeocean#1914]
See [CODEOCEAN-TW](https://codeocean.sentry.io/issues/4459598724/)

<hr>

After running into a runner or execution timeout we should send the timeout message to CodeOcean. This behavior is tested by the unit tests `TestExitHasTimeoutErrorIfRunnerTimesOut` and `TestReturnsAfterTimeout`, and the e2e test `TestCommandReturnsAfterTimeout`.

<hr>

CodeOcean shows the wrong error `Alle Ausführungsumgebungen sind momentan in Benutzung. Probiere es später nochmal.`

**Comment by mpass99** [comment]
By changing the debug level of CodeOcean to `debug`, I was able to verify that CodeOcean receives the timeout message.

![Image](https://github.com/openHPI/codeocean/assets/22845248/2bfcd547-b2cf-47b9-9694-6b1e8fd00e45)

I tried to debug the behavior of CodeOcean, but unfortunately I was not even able to get added debug statements in `connection.rb` to output :frowning_face:

**Comment by MrSerth** [comment]
Awesome, thanks for having a further look there! I thought I had a look there, but obviously I didn't.

When investigating now, I identified that the JSON response sent by Poseidon is not recognized as valid and hence not accepted:

```rb
BACKEND_OUTPUT_SCHEMA.valid?({"type": "timeout"})
=> false

BACKEND_OUTPUT_SCHEMA.valid?({"type": "start"})
=> false
```

```rb
BACKEND_OUTPUT_SCHEMA.valid?({"type": "exit", data: 0})
=> true

BACKEND_OUTPUT_SCHEMA.valid?({"type": "stdout", data: "test"})
=> true

BACKEND_OUTPUT_SCHEMA.valid?({"type": "stderr", data: "test"})
=> true

BACKEND_OUTPUT_SCHEMA.valid?({"type": "error", data: "test"})
=> true
```

The test is performed [here](https://github.com/openHPI/codeocean/blob/f47e29fae9e964ce2aebb866aaebab01f2a0045b/lib/runner/connection.rb#L123) with [this schema](https://github.com/openHPI/codeocean/blob/f47e29fae9e964ce2aebb866aaebab01f2a0045b/lib/runner/connection.rb#L10) loaded from [here](https://github.com/openHPI/codeocean/blob/3017e4600648eb02b1db2e7002cd737d7742f9b7/lib/runner/backend-output.schema.json). The library JSONSchemer we use [got recently upgraded](https://github.com/openHPI/codeocean/pull/1846).

Can you tell whether the schema and output should validate to each other or whether we see a bug in the library?

**Comment by MrSerth** [comment]
Indeed, I was able to identify that the recent JSONSchemer upgrade is responsible for the bug. Hence, I downgraded JSONSchemer with f6975ac7 and added some Sentry logging with 56b6380f to prevent further (unnoticed) issues.

I think we should proceed with testing further (is our schema valid...) and otherwise report this as a bug with a minimal reproduction example upstream. The following command might be handy for testing:

```rb
JSONSchemer.schema(JSON.parse(File.read('lib/runner/backend-output.schema.json'))).valid?({"type" => "timeout"})
```

It works with JSONSchemer 1.0.3 and fails with 2.0.0.

@mpass99 Would you mind assisting me from here?

**Comment by mpass99** [comment]
The [Online JSON Schema Validator](https://extendsclass.com/json-schema-validator.html) reports that our schema is invalid. The `required` attribute should not be at the specific property but one more outer as an array containing the required properties (such as described [in the JSON schema](https://json-schema.org/understanding-json-schema/reference/object.html#required)).

By correcting the JSON schema, the `JSONSchemer` accepts now all listed events.

``` ruby
# all true
puts BACKEND_OUTPUT_SCHEMA.valid?({"type": "timeout"})
puts BACKEND_OUTPUT_SCHEMA.valid?({"type": "start"})
puts BACKEND_OUTPUT_SCHEMA.valid?({"type": "exit", data: 0})
puts BACKEND_OUTPUT_SCHEMA.valid?({"type": "stdout", data: "test"})
puts BACKEND_OUTPUT_SCHEMA.valid?({"type": "stderr", data: "test"})
puts BACKEND_OUTPUT_SCHEMA.valid?({"type": "error", data: "test"})
```

**Comment by MrSerth** [comment]
> By correcting the JSON schema (see https://github.com/openHPI/poseidon/pull/456), the JSONSchemer accepts now all listed events.

Indeed, I was able to confirm this. Let's create a PR for CodeOcean as well :+1:.
