### ISSUE TITLE
Submitting code might fail with embed_options_disable_rfc

### ISSUE THREAD

**Issue by koelibri** [openHPI/codeocean#2004]
When using CodeOcean (from Moodle) via LTI and setting `embed_options_disable_rfc=true` the score delivery fails due to a Javascript error occurring right after clicking the submit button.  [1]

Allowing or disabling requests for comments should not interfere with submitting scores to the calling LMS (such as Moodle). Imagine the use case of an examination situation: One would not allow to request comments, while, for obvious reasons, the submission of the gained scores are mandatory.

LTI session seem to differentiate between "with outcome" and "without outcome". If this determines the score submission back to the calling LMS, then the submit button should be shown with respect to that session type. If shown, the submit button then should work properly though.  

[1]: ![Bildschirmfoto 2023-11-09 um 09 09 12](https://github.com/openHPI/codeocean/assets/23314349/f9e38ed4-6a8c-4801-9bb0-3465ca5e185a)

**Comment by MrSerth** [comment]
Many thanks for reporting your issue, @koelibri. I've aimed to reproduce the issue, but, based on the information given, wasn't able to do so. The following shows what I did and, according to my impression, everything worked well:

https://github.com/openHPI/codeocean/assets/7300329/dd3cb3ae-0ca4-450d-89ba-aced9956a047

Further, I did not saw any JavaScript error, besides using the same browser (Safari). Therefore, I would kindly ask you to provide more information on your bug:

- Which CodeOcean version are you using?
- Which browser version are you using?
- What's the stack trace of the error?
- Which steps have you taken before?
- Did you try other combination of settings, i.e., with another exercise or execution environment?
- Can you provide detailed reproduction steps, for example as a regression spec?

Moreover, please note our documentation on [supported versions](https://github.com/openHPI/codeocean/blob/master/SECURITY.md#supported-versions). As far as I can tell, the version you were using is not recent and thus not officially supported. 

Finally, I am happy to share that the dedicated submit button will soon vanish with our work on #1698. Therefore, the situation might change further.

**Comment by koelibri** [comment]
Having updated our CO instance the problem seems to be gone. 

Thank you!
