### ISSUE TITLE
Error handling when editing exercises

### ISSUE THREAD

**Issue by franzliedke** [openHPI/codeocean#212]
I have experienced this several times now, and almost always lost significant amounts of work...

When editing an exercise and (apparently) making mistakes that trip up model validations, I do not get the expected inline errors, but rather a general error message claiming that CodeOcean is down for maintenance (?).

Because so much JS is involved, using my browser's back button does not bring back the unsaved content, which means that all my work is lost. And it can be a lot of work, such as the detailed task description for an exercise, or several test files.

**Expected behavior:**

CodeOcean should treat validation errors as such, and take me back to the edit screen where all unsaved data should still be visible - along with inline error messages on each field telling me what exactly I did wrong.

**Comment by MrSerth** [comment]
Trace 3161abf0-fa8a-45eb-96da-af39b5848b24 might be related to this issue

**Comment by franzliedke** [comment]
Because I was asked about it: this is about editing exercises as a teacher, not a student's submission.

**Comment by rteusner** [comment]
We fixed this here: https://github.com/openHPI/codeocean/pull/238

**Comment by franzliedke** [comment]
It doesn't seem like #238 changes anything about the fact that validation errors will cause all entered data to be lost. So if I forget to add another required field, the data will still be gone.

**Comment by MrSerth** [comment]
The changes are not deployed so far, we’ll notify you as soon as we did so.

// cc: @rteusner

**Comment by MrSerth** [comment]
The changes are now deployed.
