### ISSUE TITLE
Exercise execution ignores file path

### ISSUE THREAD

**Issue by jgraichen** [openHPI/codeocean#221]
When I run a (main) file located in a directory I'd expect the file to be run. Instead the file (usually) not found.

The path seems to be completely ignored. If the file to be run is e.g. `bin/tasks.rb`, CodeOcean tries to run the file `tasks.rb`, which, usually, not exists.

**Comment by rteusner** [comment]
We fixed it here: https://github.com/openHPI/codeocean/pull/223
