### ISSUE TITLE
CodeOcean does not run in IE11

### ISSUE THREAD

**Issue by kaifabian** [openHPI/codeocean#30]
CodeOcean can not be executed using the Internet Explorer 11. Loading the editor fails with an error message stating that the browser is not supported.

Also see https://open.hpi.de/courses/pythonjunior2015/question/d4814ca3-fa9a-4f97-8ce2-ce32f11d3f46 for a course participant with that problem.

**Comment by Parnswir** [comment]
This issue will be fixed with #64.

**Comment by rteusner** [comment]
Indeed, it was. ;-)
