### ISSUE TITLE
STRG + ALT + 0 does nothing

### ISSUE THREAD

**Issue by jpsachse** [openHPI/codeocean#31]
Pressing `STRG + ALT + 0` in a CodeOcean editor does nothing.
Expected behavior: an `}` is inserted at the current cursor position.
Workaround: Inserting the `}` in another application and copy it over to CodeOcean or using the `ALT GR + 0` shortcut.

**Comment by Parnswir** [comment]
`(CTRL +) ALT + 0` is a feature of the underlying [Ace editor](https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts) for code folding.

**Comment by jpsachse** [comment]
If only `ALT + 0` is needed for folding, wouldn't it be possible to both allow `CTRL + ALT + 0` to behave like the system default and allow the ACE-shortcut?
