### ISSUE TITLE
Turtle Improvements

### ISSUE THREAD

**Issue by ebertmi** [openHPI/codeocean#59]
I met one of your collegues on last EDUCON in Abu Dhabi. I just want to share a couple points for improvements for the turtle rendering.

Setting a background does not work in the current code to lines [turtle.js#L44-L45](https://github.com/openHPI/codeocean/blob/cc0a541add9bcb363963beee6b46f217f01a26df/app/assets/javascripts/turtle.js#L44-L45). Replace those two lines

``` javascript
ctx.fillStyle = '#fff';
ctx.fillRect(0, 0, canvas.width, canvas.height);
```

with

``` javascript
ctx.clearRect(0, 0, canvas.width, canvas.height);
```

and setting a background color in turtle works.

Currently, the setting a `pencolor` is not possible as it is not passed to the rendering in [Line 59](https://github.com/openHPI/codeocean/blob/cc0a541add9bcb363963beee6b46f217f01a26df/app/assets/javascripts/turtle.js#L59). You can add a check the `item` for the pencolor and the fillcolor.

Regards

**Comment by rteusner** [comment]
Hi waywaaard,

yes, you are right. Just tried it out, works fine.
Many thanks for your bug report with integrated fix. ;-)
 
I believe the pencolor problem was just because we took the fill from this, and not from item.
I also fixed that.

What did you mean with "add a check" ?

Best regards,
Ralf

**Comment by waywaaard** [comment]
You also need to check for `item.outline` and and set the `ctx.strokeStyle`. You can have a thik line with and outline and different fill color.

**Comment by rteusner** [comment]
Since it was not used in the Python introduction course, the parameters are not sent by our backend yet. Therefore, it has to be added in the docker container (in the file `turtle.py`), and then consumed in the `turtle.js` apropriately. What do you want to do exactly?

Since I have no example in mind right now, I am not sure what you need.
Am open for examples and/or pull requests of course.

**Comment by MrSerth** [comment]
Many thanks again for your report, @ebertmi.

With commit c19f8b9a, we also support setting a line width. That has been used in a large-scale MOOC three years ago, so I think it's bullet-proof by now.

One of the example pictures [created by one of the learners](https://open.hpi.de/courses/pythonjunior2020/question/69f183a5-3219-4ae8-a9ca-fda8ebc6b815) called _Christian S._ showing different line thicknesses, background colours and pen colours was the following:

<details><summary>Source code</summary>
<p>

```python
from turtle import *

# allgemeine Werte
colormode( 255 )
bgcolor(66, 135, 245)
hideturtle()
speed(0)

#Fahne  ******************
pencolor("black")
fillcolor(216, 222, 232)
penup(); goto(-180,-50); pendown()
width(1)
begin_fill()
left(88); forward(60)
left(4); forward(60)
left(4); forward(60)
right(4); forward(60)

right(90); forward(60)
right(6); forward(180)
left(4); forward(60)
right(4); forward(80)

right(90); forward(80)
left(4); forward(60)
right(7); forward(80)
left(7); forward(20)
right(98); forward(60)
left(2); forward(60)
left(6); forward(60)
left(4); forward(60)
goto(-180,-50)
end_fill()



# Olympische Ringe *************
penup(); home(); pendown()
pensize(10)

# Blauer Ring
pencolor("blue")
penup(); goto(-92,50); pendown()
left(35)
circle(50,360)

# Gelber Ring
pencolor("yellow")
penup(); goto(-83,84); pendown()
left(165)
circle(50,332)

# Schwarzer Ring
pencolor("black")
penup(); goto(-51,73); pendown()
left(117)
circle(50,332)

# Grüner Ring
pencolor("green")
penup(); goto(35,82); pendown()
right(60)
circle(50,335)

# Roter Ring
pencolor("red")
penup(); goto(63,74); pendown()
left(109)
circle(50,338)

# Fahnenmast *******************
penup(); home(); pendown()
pensize(1)
fillcolor(84, 60, 14)
pencolor("black")
penup(); goto(-198,-198); pendown()

begin_fill()
left(90)
forward(396)
right(90)
forward(8)
right(90)
forward(396)
right(90)
forward(8)
end_fill()

# Schnüre ************************
penup(); home(); pendown()
pensize(3)
pencolor("black")
penup(); goto(-180,-50); pendown()
right(165)
forward(10)

penup(); home(); pendown()
pensize(3)
penup(); goto(-189,190); pendown()
right(30)
forward(4)
```

</p>
</details> 

![Olympische_Flagge](https://github.com/openHPI/codeocean/assets/7300329/bc7eaf28-3ef6-43a1-92ee-5521d1da62eb)

Therefore, I am closing this issue as being complete. Please feel free to reach out if you have any other question or suggestion. Thanks again and many greetings from Potsdam!
