### ISSUE TITLE
Add project description to README.md

### ISSUE THREAD

**Issue by winnewoerp** [openHPI/codeocean#648]
README.md shoud start with a general description answering the follwing question (nd maybe more): What is CodeOdean exactly? What's it used for and what goals can be achieved when using it? Who started it and what for?

Installation/usage instructions should start after this short description.

**Comment by MrSerth** [comment]
Hi @winnewoerp,

thanks for taking a look and opening your first issue within the openHPI organization. I added a summary answering most of your questions with 4e638ca539f9689604d3beb8d45d0d6e76503560.
