### ISSUE TITLE
Set the file type of files automatically to the Execution Environment

### ISSUE THREAD

**Issue by arneboockmeyer** [openHPI/codeocean#8]

**Comment by hklement** [comment]
You mean when creating a Java exercise, the type of new files should default to `.java`, right?

**Comment by arneboockmeyer** [comment]
Yes, the File Type should be Java, when the Execution Environment is Java

**Comment by hklement** [comment]
Implemented in commit 3ae749bfc591f8a9e11bcf7115d66976146ee252.
