### ISSUE TITLE
Ratings not working

### ISSUE THREAD

**Issue by kirstin** [openHPI/codeocean#85]
On the live instance of [CodeHarbor](https://tools.openhpi.de/codeharbor/) the rating of exercises does not work. 

If a user clicks on one of the stars in an attempt to rate an exercise, a 404 page appears.   
This is the url that is queried: "https://tools.openhpi.de/exercises/1/ratings?rating[rating]=3"

The url needs to begin with "https://tools.openhpi.de/codeharbor/". This is clearly not the case. 

Todo:

- [ ] fix URLs for rating

**Comment by Parnswir** [comment]
How is this related to CodeOcean? CodeHarbor lives over here: https://github.com/openHPI/codeharbor

**Comment by tstaubitz** [comment]
That's definitely wrong here. It also is outdated. So I just close it.
